# -*- coding: utf-8 -*-
"""sample video.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D4fqvr_G69gIxZ3f9Ojl1If39cDKQH8X
"""

import cv2
import pandas as pd

# Read the video file
video_path = 'vids/train/10_1.mp4'
cap = cv2.VideoCapture(video_path)

# Read the bounding box coordinates from the CSV file
csv_path = 'mot_clean/train/10_1.txt'
df = pd.read_csv(csv_path)

# Iterate through each frame
while True:
    ret, frame = cap.read()
    if not ret:
        # Reset the video capture to the beginning
        cap.set(cv2.CAP_PROP_POS_FRAMES, 0)
        continue

    # Get the bounding box coordinates for the current frame
    frame_number = int(cap.get(cv2.CAP_PROP_POS_FRAMES))
    frame_boxes = df[df['frame'] == frame_number]

    # Draw bounding boxes on the frame
    for _, row in frame_boxes.iterrows():
        x, y, x_offset, y_offset, obj_id = int(row['x']), int(row['y']), int(row['x_offset']), int(row['y_offset']), int(row['id'])
        xmin, ymin, xmax, ymax = x, y, x + x_offset, y + y_offset

        # Draw bounding box
        cv2.rectangle(frame,(xmin, ymin), (xmax, ymax), (0, 255, 0), 2)

        # Display object id
        cv2.putText(frame, f"ID: {obj_id}", (xmin, ymin - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

    # Display the frame with bounding boxes
    cv2.imshow('Frame', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the video capture and close windows
cap.release()
cv2.destroyAllWindows()
